# Generated by Django 5.2.4 on 2025-09-03 12:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#007bff", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FileStorage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("extension", models.CharField(max_length=20)),
                ("checksum", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["uuid"], name="filemanager_uuid_419ab0_idx"),
                    models.Index(
                        fields=["original_filename"],
                        name="filemanager_origina_a350ec_idx",
                    ),
                    models.Index(
                        fields=["mime_type"], name="filemanager_mime_ty_d75a00_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FileThumbnail",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("thumbnail_path", models.CharField(max_length=500)),
                ("thumbnail_size", models.CharField(max_length=20)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("file_size", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "original_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnails",
                        to="filemanager.filestorage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("file", "File"), ("directory", "Directory")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("user", "User Shared"),
                            ("group", "Group Shared"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="filemanager.fileitem",
                    ),
                ),
                (
                    "shared_groups",
                    models.ManyToManyField(
                        blank=True, related_name="shared_files", to="auth.group"
                    ),
                ),
                (
                    "shared_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "storage",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filemanager.filestorage",
                    ),
                ),
                (
                    "thumbnail",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="filemanager.filethumbnail",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FileAccessPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("read", "Read"),
                            ("write", "Write"),
                            ("delete", "Delete"),
                            ("share", "Share"),
                            ("admin", "Admin"),
                        ],
                        max_length=10,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        help_text="Higher priority overrides lower priority permissions",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_permissions",
                        to="auth.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_permissions",
                        to="filemanager.fileitem",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["file", "user", "permission_type"],
                        name="filemanager_file_id_692231_idx",
                    ),
                    models.Index(
                        fields=["file", "group", "permission_type"],
                        name="filemanager_file_id_c50120_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "is_active"],
                        name="filemanager_expires_fc6b56_idx",
                    ),
                    models.Index(
                        fields=["priority"], name="filemanager_priorit_323ddf_idx"
                    ),
                ],
                "unique_together": {
                    ("file", "group", "permission_type"),
                    ("file", "user", "permission_type"),
                },
            },
        ),
        migrations.CreateModel(
            name="FileAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("download", "Download"),
                            ("edit", "Edit"),
                            ("delete", "Delete"),
                            ("upload", "Upload"),
                            ("permission_granted", "Permission Granted"),
                            ("permission_revoked", "Permission Revoked"),
                            ("visibility_change", "Visibility Change"),
                            ("shared", "Shared"),
                            ("unshared", "Unshared"),
                            ("user_shared", "User Shared"),
                            ("group_shared", "Group Shared"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="filemanager.fileitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["file", "timestamp"],
                        name="filemanager_file_id_12abc4_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="filemanager_user_id_a2df4c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FilePermissionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_permissions", models.CharField(max_length=100)),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_requests",
                        to="filemanager.fileitem",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewed_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["file", "status"], name="filemanager_file_id_7d4f00_idx"
                    ),
                    models.Index(
                        fields=["requester", "status"],
                        name="filemanager_request_f003f3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FileTagRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_relations",
                        to="filemanager.fileitem",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_relations",
                        to="filemanager.filetag",
                    ),
                ),
            ],
            options={
                "unique_together": {("file", "tag")},
            },
        ),
        migrations.AddIndex(
            model_name="filethumbnail",
            index=models.Index(
                fields=["original_file"], name="filemanager_origina_aa663e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filethumbnail",
            index=models.Index(
                fields=["thumbnail_size"], name="filemanager_thumbna_9c5183_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileitem",
            index=models.Index(
                fields=["item_type"], name="filemanager_item_ty_942d3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileitem",
            index=models.Index(
                fields=["parent"], name="filemanager_parent__c8ff1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileitem",
            index=models.Index(
                fields=["visibility"], name="filemanager_visibil_16ba84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileitem",
            index=models.Index(fields=["owner"], name="filemanager_owner_i_38d3c1_idx"),
        ),
        migrations.AddIndex(
            model_name="fileitem",
            index=models.Index(
                fields=["is_deleted"], name="filemanager_is_dele_2c1ff7_idx"
            ),
        ),
    ]
