# Generated by Django 5.2.4 on 2025-09-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaccesslog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
