# Generated by Django 5.2.4 on 2025-08-27 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('filemanager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('delete', 'Delete'), ('share', 'Share'), ('admin', 'Admin')], max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilePermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_permissions', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='filesystemitem',
            name='is_public',
        ),
        migrations.AddField(
            model_name='filesystemitem',
            name='shared_groups',
            field=models.ManyToManyField(blank=True, related_name='shared_files', to='auth.group'),
        ),
        migrations.AddField(
            model_name='filesystemitem',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('public', 'Public')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='fileaccesslog',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('edit', 'Edit'), ('delete', 'Delete'), ('upload', 'Upload'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('visibility_change', 'Visibility Change'), ('shared', 'Shared'), ('unshared', 'Unshared')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='filesystemitem',
            index=models.Index(fields=['visibility'], name='filemanager_visibil_51a011_idx'),
        ),
        migrations.AddIndex(
            model_name='filesystemitem',
            index=models.Index(fields=['owner'], name='filemanager_owner_i_4622d0_idx'),
        ),
        migrations.AddField(
            model_name='fileaccesspermission',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='filemanager.filesystemitem'),
        ),
        migrations.AddField(
            model_name='fileaccesspermission',
            name='granted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileaccesspermission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_permissions', to='auth.group'),
        ),
        migrations.AddField(
            model_name='fileaccesspermission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filepermissionrequest',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='filemanager.filesystemitem'),
        ),
        migrations.AddField(
            model_name='filepermissionrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filepermissionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fileaccesspermission',
            index=models.Index(fields=['file', 'user', 'permission_type'], name='filemanager_file_id_692231_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesspermission',
            index=models.Index(fields=['file', 'group', 'permission_type'], name='filemanager_file_id_c50120_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesspermission',
            index=models.Index(fields=['expires_at', 'is_active'], name='filemanager_expires_fc6b56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fileaccesspermission',
            unique_together={('file', 'group', 'permission_type'), ('file', 'user', 'permission_type')},
        ),
        migrations.AddIndex(
            model_name='filepermissionrequest',
            index=models.Index(fields=['file', 'status'], name='filemanager_file_id_7d4f00_idx'),
        ),
        migrations.AddIndex(
            model_name='filepermissionrequest',
            index=models.Index(fields=['requester', 'status'], name='filemanager_request_f003f3_idx'),
        ),
    ]
