# Generated by Django 5.2.11 on 2026-02-24 02:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filemanager", "0002_fix_ip_address_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileitem",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
