# Generated by Django 5.2.4 on 2025-08-27 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('filemanager', '0002_fileaccesspermission_filepermissionrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fileaccesspermission',
            name='priority',
            field=models.IntegerField(default=1, help_text='Higher priority overrides lower priority permissions'),
        ),
        migrations.AddField(
            model_name='filesystemitem',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileaccesslog',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('edit', 'Edit'), ('delete', 'Delete'), ('upload', 'Upload'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('visibility_change', 'Visibility Change'), ('shared', 'Shared'), ('unshared', 'Unshared'), ('user_shared', 'User Shared'), ('group_shared', 'Group Shared')], max_length=20),
        ),
        migrations.AlterField(
            model_name='filesystemitem',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('user', 'User Shared'), ('group', 'Group Shared'), ('public', 'Public')], default='private', max_length=10),
        ),
        migrations.AddIndex(
            model_name='fileaccesspermission',
            index=models.Index(fields=['priority'], name='filemanager_priorit_323ddf_idx'),
        ),
    ]
