# Generated by Django 5.2.4 on 2025-08-27 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('filemanager', '0003_fileaccesspermission_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filesystemitem',
            name='relative_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddIndex(
            model_name='filesystemitem',
            index=models.Index(fields=['relative_path'], name='filemanager_relativ_b553c4_idx'),
        ),
    ]
