# Generated by Django 5.2.4 on 2025-09-02 01:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0005_filesystemitem_deleted_at_filesystemitem_deleted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=20)),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileThumbnail',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('thumbnail_path', models.CharField(max_length=500)),
                ('thumbnail_size', models.CharField(max_length=20)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('file_size', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='filesystemitem',
            name='filemanager_path_a3cb9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='filesystemitem',
            name='filemanager_relativ_b553c4_idx',
        ),
        migrations.RemoveField(
            model_name='filesystemitem',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='filesystemitem',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='filesystemitem',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='filesystemitem',
            name='path',
        ),
        migrations.RemoveField(
            model_name='filesystemitem',
            name='relative_path',
        ),
        migrations.RemoveField(
            model_name='filesystemitem',
            name='size',
        ),
        migrations.AddIndex(
            model_name='filestorage',
            index=models.Index(fields=['uuid'], name='filemanager_uuid_419ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='filestorage',
            index=models.Index(fields=['original_filename'], name='filemanager_origina_a350ec_idx'),
        ),
        migrations.AddIndex(
            model_name='filestorage',
            index=models.Index(fields=['mime_type'], name='filemanager_mime_ty_d75a00_idx'),
        ),
        migrations.AddField(
            model_name='filesystemitem',
            name='storage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filemanager.filestorage'),
        ),
        migrations.AddField(
            model_name='filethumbnail',
            name='original_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='filemanager.filestorage'),
        ),
        migrations.AddField(
            model_name='filesystemitem',
            name='thumbnail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filemanager.filethumbnail'),
        ),
        migrations.AddIndex(
            model_name='filethumbnail',
            index=models.Index(fields=['original_file'], name='filemanager_origina_aa663e_idx'),
        ),
        migrations.AddIndex(
            model_name='filethumbnail',
            index=models.Index(fields=['thumbnail_size'], name='filemanager_thumbna_9c5183_idx'),
        ),
    ]
