# Generated by Django 5.2.4 on 2025-09-02 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('filemanager', '0006_filestorage_filethumbnail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='filesystemitem',
            constraint=models.UniqueConstraint(condition=models.Q(('item_type', 'directory')), fields=('name', 'parent', 'item_type', 'owner'), name='unique_directory_name_per_parent_per_owner'),
        ),
    ]
