# Generated by Django 5.2.4 on 2025-09-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0008_fix_directory_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='filesystemitem',
            name='unique_directory_name_per_parent_per_owner',
        ),
    ]
