# Generated by Django 5.2.4 on 2025-09-03 02:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('filemanager', '0009_remove_constraint_add_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileSystemItem',
            new_name='FileItem',
        ),
        migrations.RenameIndex(
            model_name='fileitem',
            new_name='filemanager_item_ty_942d3a_idx',
            old_name='filemanager_item_ty_91d9c8_idx',
        ),
        migrations.RenameIndex(
            model_name='fileitem',
            new_name='filemanager_parent__c8ff1f_idx',
            old_name='filemanager_parent__0b32e6_idx',
        ),
        migrations.RenameIndex(
            model_name='fileitem',
            new_name='filemanager_visibil_16ba84_idx',
            old_name='filemanager_visibil_51a011_idx',
        ),
        migrations.RenameIndex(
            model_name='fileitem',
            new_name='filemanager_owner_i_38d3c1_idx',
            old_name='filemanager_owner_i_4622d0_idx',
        ),
        migrations.RenameIndex(
            model_name='fileitem',
            new_name='filemanager_is_dele_2c1ff7_idx',
            old_name='filemanager_is_dele_adef9d_idx',
        ),
    ]
